version: "3.7"
services:
  database-sys-api-sb:
    container_name: database-sys-api-sb-prod
    image: bananaztech/database-sys-api-sb:latest
    restart: always
    ports:
      - "8091:8080"
      - "8007:9000"
